### ISSUE TITLE
Feature Request: Make so mod is optional client side

### ISSUE THREAD

**Issue by lawl281** [Buuz135/FindMe#1]
Allowing me to add this to my server then put in server message that the mod is optional rather than forcing all users (both those who want this and don't) to add the mod makes it unmanagble for servers when the modpack doesn't have this in it.  Either releasing a private version of a modpack or forcing everyone who wants to join a server to modify their modpack doesn't work for all users.

**Comment by Buuz135** [comment]
Impossible
