### ISSUE TITLE
prevent correct rendering of other mods

### ISSUE THREAD

**Issue by krakel** [Buuz135/FindMe#20]
After some tests I found the mod prevent the correct rendering of encoded patterns of AE2 (at the interface table).

**Comment by k3nw4y** [comment]
![image](https://user-images.githubusercontent.com/46229190/150545411-ff5f4b25-f84f-411d-a1ca-da14a6f1cc67.png)

**Comment by Technici4n** [comment]
Fixed by https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6132.
