### ISSUE TITLE
Search feature does not work in JEI's recipe viewer

### ISSUE THREAD

**Issue by genandnic** [Buuz135/FindMe#3]
The search feature doesn't seem to work when hovering over an item in JEI's recipe viewer. This is an issue because you often need to search for items that you don't currently have for those recipes.

**Comment by KaneHart** [comment]
Sad this never happen. Anyone find a alternative mod outside the bloated Extra Utilities?

**Comment by KaneHart** [comment]
Another request on this feature if possible be having it also on the bookmark recipes on the left side. I think that is a newer JEI feature.

**Comment by Buuz135** [comment]
https://github.com/Buuz135/FindMe/commit/dbdd3beb47ca13db8a0e5fa1d262f3178e410017
