### ISSUE TITLE
Client crash on server when pressing FindMe keybind (Y) while hover an item in inventory

### ISSUE THREAD

**Issue by trunksbomb** [Buuz135/FindMe#47]
https://mclo.gs/MRyeLDn

MC 1.21.1
NeoForge 21.1.77
FindMe 3.3.1

This is on the [Craftoria modpack v1.8.0](https://www.curseforge.com/minecraft/modpacks/craftoria). I wasn't able to replicate in single player or LAN on the same modpack, so it seems to be server specific.

When I press `Y` in my inventory while hovering over an inventory item, the client crashes with error 

```
[Render thread/ERROR] [ne.ne.bu.EventBus/EVENTBUS]: Exception caught during firing event: Payload findme:position_request may not be sent to the server!
```

I see that there's a 3.3.2 version available but I didn't see anything regarding this error in the commits, so not sure if it's resolved there. I'm aware this also could be a modpack-specific issue or even an issue specifically with the official Craftoria server as they may have made changes beyond the official configuration of the pack.

**Comment by Linguardium** [comment]
3.3.2 is not built for 1.21.1.  

Mod worked fine on fresh server install with both a fresh client and a client updated from 1.7.1 to 1.7.2 to 1.8.0.

**Comment by trunksbomb** [comment]
You bring up an interesting point that I didn't consider - the official server seems to have gone straight from Craftoria v1.6.1 to Craftoria v1.8.0. That was the upgrade path I took.

**Comment by Linguardium** [comment]
Ah, you mean the server that the AOE team hosts. seems to be an issue with their server which does not have the same mod loadout or settings as the serverpack that they provide. I'll follow up with them there.

**Comment by trunksbomb** [comment]
I figured that would be the case, the official servers from Team AOF usually have additional modifications over the base server pack.

**Comment by trunksbomb** [comment]
Issue is resolved - server was missing the mod altogether. Pressing the FindMe keybind does not crash my client now.

**Comment by trunksbomb** [comment]
Issue is resolved - server was missing the mod altogether. Pressing the FindMe keybind does not crash my client now.
